'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

from functools import reduce

def makeFib(maxVal):
    fib = [1, 2]
    while True:
        next = fib[-1] + fib[-2]
        if next >= maxVal:
            return fib
        fib.append(next)

print(reduce(lambda x, y: x+y, [i for i in makeFib(4000000) if i % 2 == 0]))
